# 1. Array Creation Function

In [4]:
import numpy as np

In [8]:
# Create an array from a list
a = np.array([1,2,3])
print("Array a:", a)


Array a: [1 2 3]


In [10]:
# Create an array with evenly spaced values
b=np.arange(0,10,2)  # values from 0 to 10 with step 2
print("Array b:",b)

Array b: [0 2 4 6 8]


In [38]:
# Create an array with linearly spaced values
c = np.linspace(0,1,5) # 5 values evenly spaced between 0 and 1
print("Array c:",c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [14]:
# create an array filled with zeros
d = np.zeros((2,3)) # 2x3 array of zeros
print("Array d:\n", d)


Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [16]:
# create an array filled with ones
e = np.ones((3,2)) # 3x2 array of ones
print("Array e:\n",e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
# create an identity matrix
f = np.eye(4) # 4x4 identity matrix
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2. Array Manipulation functions

In [26]:
# Reshape an array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1, (1,3)) # Reshape to 1x3 matrix
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]]


In [28]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1, (3,1))
print("Reshaped array:", reshaped)

Reshaped array: [[1]
 [2]
 [3]]


In [30]:
# Flatten an Array
f1 = np.array([[1,2],[3,4]])
flattened = np.ravel(f1) # Flatten to 1D array
print("Flattened array:", flattened)

Flattened array: [1 2 3 4]


In [34]:
# Transpose an array
e1=np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("Transposed array:", transposed)

Transposed array: [[1 3]
 [2 4]]


In [42]:
# stack arrays vertically
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2]) # Stack a and b vertically
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


In [49]:
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.hstack([a2,b2]) # Stack a and b horizontally
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [1 2 3 4]


In [59]:
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.dstack([a2,b2]) # Stack a and b depth wise 
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[[1 3]
  [2 4]]]


In [53]:
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.row_stack([a2,b2]) 
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


In [55]:
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.column_stack([a2,b2]) 
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 3]
 [2 4]]


In [57]:
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.stack([a2,b2]) 
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


# 3.Mathematical Function

In [45]:
# Add two arrays
g = np.array([1,2,3,4])
added = np.add(g,2) # add 2 to each element
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [65]:
# Square each element
squared = np.power(g,2) # Square each element
print("Squared g:", squared)

Squared g: [ 1  4  9 16]


In [67]:
# square root of each element
sqrt_val = np.sqrt(g)
print("Square root of g:", sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [69]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [75]:
# Dot product of two arrays
a2 = np.array([1,2,3])
dot_product = np.dot(a2,g)
print("Dot product of a2 and g:", dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [77]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [81]:
a3 = np.array([1,2,3])
dot_product = np.dot(a1,a) # Dot product of a and g
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 14


# 4. Statistical Functions

In [86]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print("Mean of s:",mean)

Mean of s: 2.5


In [88]:
# standard deviation of an array
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [90]:
# Minimum element of an array
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [92]:
# Maximum element of an arary
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


# 5.Linear Algebra Functions

In [95]:
# create a matrix
matrix = np.array([[1,2],[3,4]])

In [99]:
# Determinant of a matrix
determinant = np.linalg.det(matrix)
print("Determinant of matrix:", determinant)

Determinant of matrix: -2.0000000000000004


In [101]:
# Inverse of a matrix
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# 6. Random sampling Functions

In [106]:
# Generate random values between 0 and 1
random_vals = np.random.rand(3) # array of 3 random values between 0 and 1
print("Random values:", random_vals)


Random values: [0.23996055 0.00248772 0.39705296]


In [108]:
# set seed for reproducibility
np.random.seed(0)

# Generate random values between 0 and 1
random_vals = np.random.rand(3)
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [112]:
# Generate random integers
rand_ints = np.random.randint(0,10, size=5) # Random integer between 0 and 10
print("Random integers:", rand_ints)

Random integers: [2 4 7 6 8]


In [114]:
# set seed for reproducibility
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0,10, size=5) # Random integer between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


# 7. Boolean & Logical Functions

In [117]:
# check if all elements are true
# all
logical_test = np.array([True,False,True])
all_true = np.all(logical_test) # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [119]:
# Check if all elements are True
logical_test = np.array([True,False,True])
all_true = np.all(logical_test)
print("All elements True:", all_true)

All elements True: False


In [121]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [125]:
# check if any elements are true
# any
any_true = np.any(logical_test) # check if any are true
print("Any elements True:", any_true)

Any elements True: False


# 8.Set Operations

In [128]:
# Intersection of two arrays
set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [130]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


# 9. Array Attribute Functions

In [133]:
# array attributes
a = np.array([1,2,3])
shape = a.shape # shape of the array
size = a.size # Number of elements
dimensions = a.ndim # Number of dimensions
dtype = a.dtype # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of simensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of simensions of a: 1
Data type of a: int32


# 10. Other Functions

In [142]:
# Create a copy of an array
a = np.array([1,2,3])
copied_array = np.copy(a) # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [146]:
# Size in Bytes of an array
array_size_in_bytes = a.nbytes # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 12


In [148]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array) # check if arrays share memory
print("Do a and copied_array share memory?",shared)

Do a and copied_array share memory? False
