# 30 April

# Numpy

In [5]:
import numpy as np

In [7]:
np.__version__

'1.26.4'

In [9]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# Creating List

In [12]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [15]:
type(my_list)

list

# Converting list to array

In [19]:
# !pip install numpy

In [23]:
arr=np.array(my_list)

In [25]:
arr

array([0, 1, 2, 3, 4, 5])

In [27]:
type(my_list)

list

In [ ]:
np. # we learn important function

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(3.0)

array([0., 1., 2.])

In [39]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [41]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [45]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
np.arange(20,10) # 1st arg<2nd arg

array([], dtype=int32)

In [51]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [53]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [55]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [57]:
ar = np.arange(-30,20)
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [59]:
np.arange(10,30,5) # 10 -starting from 30- end point 5 -step count

array([10, 15, 20, 25])

In [63]:
np.zeros(10) # parameter tunning  # float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
np.zeros(10,dtype=int)    #int values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [71]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [73]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [81]:
np.zeros((10,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [83]:
np.ones(3)

array([1., 1., 1.])

In [87]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [89]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [177]:
np.twos((2,3)) # two isn't function

AttributeError: module 'numpy' has no attribute 'twos'

In [175]:
np.three((2,4)) # three isn't a function

AttributeError: module 'numpy' has no attribute 'three'

In [179]:
random.rand(3,2) 

NameError: name 'random' is not defined

In [105]:
np.random.rand(5)

array([0.86937972, 0.72012659, 0.78618939, 0.27290226, 0.9436607 ])

In [107]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [109]:
np.random.rand(3,4)

array([[0.4883615 , 0.20173254, 0.25766325, 0.76621636],
       [0.75572056, 0.21789787, 0.10149799, 0.23525565],
       [0.314346  , 0.54081846, 0.58787627, 0.72097296]])

In [122]:
np.random.randint(4,6)

5

In [124]:
np.random.randint(2,20)

18

In [133]:
np.random.randint(2,20,5)

array([10, 19, 10, 19,  6])

In [135]:
np.random.randint(10,20,5)

array([17, 14, 18, 19, 18])

In [141]:
np.random.randint(10,40,(10,10))

array([[30, 11, 36, 32, 28, 23, 29, 28, 30, 27],
       [23, 35, 10, 20, 22, 17, 12, 29, 36, 13],
       [35, 24, 33, 20, 33, 26, 19, 33, 10, 34],
       [13, 37, 13, 13, 39, 15, 28, 27, 11, 18],
       [27, 10, 34, 38, 25, 26, 18, 28, 36, 10],
       [15, 24, 36, 10, 11, 27, 22, 26, 13, 17],
       [13, 19, 27, 36, 15, 31, 38, 28, 28, 16],
       [38, 26, 18, 29, 29, 25, 26, 39, 25, 35],
       [32, 31, 10, 39, 33, 28, 19, 30, 11, 28],
       [34, 11, 24, 24, 39, 22, 17, 23, 22, 17]])

In [143]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [181]:
np.arange(1,13).reshape(5,4)  # x*y should be equal to lenth of array

ValueError: cannot reshape array of size 12 into shape (5,4)

In [151]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [161]:
b=np.random.randint(10,20,(5,4))
b

array([[19, 16, 11, 10],
       [10, 17, 10, 10],
       [18, 17, 18, 18],
       [11, 11, 11, 14],
       [12, 14, 12, 13]])

In [163]:
type(b)

numpy.ndarray

# Slicing in Matrix

In [184]:
b

array([[19, 16, 11, 10],
       [10, 17, 10, 10],
       [18, 17, 18, 18],
       [11, 11, 11, 14],
       [12, 14, 12, 13]])

In [167]:
b[:]

array([[19, 16, 11, 10],
       [10, 17, 10, 10],
       [18, 17, 18, 18],
       [11, 11, 11, 14],
       [12, 14, 12, 13]])

In [169]:
b[1:3]

array([[10, 17, 10, 10],
       [18, 17, 18, 18]])