# 1st May

# Slicing in Matrix

In [4]:
import numpy as np

In [14]:
np.__version__

'1.26.4'

In [6]:

b = np.random.randint(10,20,(5,4))
b

array([[15, 16, 15, 16],
       [16, 12, 19, 18],
       [15, 19, 16, 13],
       [17, 12, 10, 12],
       [19, 12, 12, 12]])

In [8]:
b[:]

array([[15, 16, 15, 16],
       [16, 12, 19, 18],
       [15, 19, 16, 13],
       [17, 12, 10, 12],
       [19, 12, 12, 12]])

In [10]:
b[0:2]

array([[15, 16, 15, 16],
       [16, 12, 19, 18]])

In [12]:
b

array([[15, 16, 15, 16],
       [16, 12, 19, 18],
       [15, 19, 16, 13],
       [17, 12, 10, 12],
       [19, 12, 12, 12]])

In [18]:
b[1:3]

array([[16, 12, 19, 18],
       [15, 19, 16, 13]])

In [16]:
b[0:-1]

array([[15, 16, 15, 16],
       [16, 12, 19, 18],
       [15, 19, 16, 13],
       [17, 12, 10, 12]])

In [20]:
b[2:-3]

array([], shape=(0, 4), dtype=int32)

In [22]:
b

array([[15, 16, 15, 16],
       [16, 12, 19, 18],
       [15, 19, 16, 13],
       [17, 12, 10, 12],
       [19, 12, 12, 12]])

In [24]:
b[0,2]

15

In [28]:
c = np.random.randint(10,20,(4,4))

In [30]:
c

array([[14, 10, 14, 18],
       [17, 15, 11, 14],
       [11, 12, 15, 12],
       [16, 16, 13, 18]])

In [32]:
c[2:4]

array([[11, 12, 15, 12],
       [16, 16, 13, 18]])

In [34]:
c[:-1]

array([[14, 10, 14, 18],
       [17, 15, 11, 14],
       [11, 12, 15, 12]])

In [36]:
c

array([[14, 10, 14, 18],
       [17, 15, 11, 14],
       [11, 12, 15, 12],
       [16, 16, 13, 18]])

In [39]:
c[-3:1]

array([], shape=(0, 4), dtype=int32)

In [41]:
c[-3:2]

array([[17, 15, 11, 14]])

In [45]:
c

array([[14, 10, 14, 18],
       [17, 15, 11, 14],
       [11, 12, 15, 12],
       [16, 16, 13, 18]])

In [47]:
c[2,3]

12

In [49]:
c[3,2]

13

In [51]:
c[-2,-3]

12

# Operations

In [54]:
a = np.random.randint(10,20,5)
a

array([15, 19, 17, 15, 19])

In [70]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [84]:
l1 = [0,1,2,3,4,5]
l1

[0, 1, 2, 3, 4, 5]

In [86]:
type(l1)


list

In [88]:
arr = np.array(l1)

In [90]:
arr

array([0, 1, 2, 3, 4, 5])

In [94]:
arr2 = np.random.randint(0,100,(10,10))

In [96]:
arr2

array([[71, 28, 53, 92, 70, 66, 30, 87, 18,  5],
       [11,  0, 12, 16, 12, 80, 45, 15, 77, 18],
       [43, 62, 46, 35, 14, 13, 45, 32, 28, 74],
       [40, 80, 90, 34, 11, 74, 96, 20,  2, 78],
       [59, 77,  1,  5, 63, 31, 64, 12, 23, 68],
       [71, 97, 49, 44,  3, 42, 41, 44, 23, 96],
       [ 6, 39, 32, 95, 81,  8, 85, 60, 10, 16],
       [12, 77, 67, 78, 33, 22, 79, 84, 44, 87],
       [62, 61, 27, 19, 12, 32, 27, 40, 21, 57],
       [33, 42, 93,  5, 79, 85, 16, 49, 25, 63]])

In [98]:
arr

array([0, 1, 2, 3, 4, 5])

In [100]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [102]:
arr[:4]

array([0, 1, 2, 3])

In [104]:
arr2[:]

array([[71, 28, 53, 92, 70, 66, 30, 87, 18,  5],
       [11,  0, 12, 16, 12, 80, 45, 15, 77, 18],
       [43, 62, 46, 35, 14, 13, 45, 32, 28, 74],
       [40, 80, 90, 34, 11, 74, 96, 20,  2, 78],
       [59, 77,  1,  5, 63, 31, 64, 12, 23, 68],
       [71, 97, 49, 44,  3, 42, 41, 44, 23, 96],
       [ 6, 39, 32, 95, 81,  8, 85, 60, 10, 16],
       [12, 77, 67, 78, 33, 22, 79, 84, 44, 87],
       [62, 61, 27, 19, 12, 32, 27, 40, 21, 57],
       [33, 42, 93,  5, 79, 85, 16, 49, 25, 63]])

In [108]:
arr2[0:2]

array([[71, 28, 53, 92, 70, 66, 30, 87, 18,  5],
       [11,  0, 12, 16, 12, 80, 45, 15, 77, 18]])

In [110]:
arr2[0:6]

array([[71, 28, 53, 92, 70, 66, 30, 87, 18,  5],
       [11,  0, 12, 16, 12, 80, 45, 15, 77, 18],
       [43, 62, 46, 35, 14, 13, 45, 32, 28, 74],
       [40, 80, 90, 34, 11, 74, 96, 20,  2, 78],
       [59, 77,  1,  5, 63, 31, 64, 12, 23, 68],
       [71, 97, 49, 44,  3, 42, 41, 44, 23, 96]])

In [112]:
arr2

array([[71, 28, 53, 92, 70, 66, 30, 87, 18,  5],
       [11,  0, 12, 16, 12, 80, 45, 15, 77, 18],
       [43, 62, 46, 35, 14, 13, 45, 32, 28, 74],
       [40, 80, 90, 34, 11, 74, 96, 20,  2, 78],
       [59, 77,  1,  5, 63, 31, 64, 12, 23, 68],
       [71, 97, 49, 44,  3, 42, 41, 44, 23, 96],
       [ 6, 39, 32, 95, 81,  8, 85, 60, 10, 16],
       [12, 77, 67, 78, 33, 22, 79, 84, 44, 87],
       [62, 61, 27, 19, 12, 32, 27, 40, 21, 57],
       [33, 42, 93,  5, 79, 85, 16, 49, 25, 63]])

In [114]:
arr2[4:-2]

array([[59, 77,  1,  5, 63, 31, 64, 12, 23, 68],
       [71, 97, 49, 44,  3, 42, 41, 44, 23, 96],
       [ 6, 39, 32, 95, 81,  8, 85, 60, 10, 16],
       [12, 77, 67, 78, 33, 22, 79, 84, 44, 87]])

In [126]:
arr2[1:-5]

array([[11,  0, 12, 16, 12, 80, 45, 15, 77, 18],
       [43, 62, 46, 35, 14, 13, 45, 32, 28, 74],
       [40, 80, 90, 34, 11, 74, 96, 20,  2, 78],
       [59, 77,  1,  5, 63, 31, 64, 12, 23, 68]])

In [130]:
arr2[1:5]

array([[11,  0, 12, 16, 12, 80, 45, 15, 77, 18],
       [43, 62, 46, 35, 14, 13, 45, 32, 28, 74],
       [40, 80, 90, 34, 11, 74, 96, 20,  2, 78],
       [59, 77,  1,  5, 63, 31, 64, 12, 23, 68]])

In [133]:
 arr2[2:7]

array([[43, 62, 46, 35, 14, 13, 45, 32, 28, 74],
       [40, 80, 90, 34, 11, 74, 96, 20,  2, 78],
       [59, 77,  1,  5, 63, 31, 64, 12, 23, 68],
       [71, 97, 49, 44,  3, 42, 41, 44, 23, 96],
       [ 6, 39, 32, 95, 81,  8, 85, 60, 10, 16]])

In [136]:
arr[-3:2]

array([], dtype=int32)

In [138]:
arr2

array([[71, 28, 53, 92, 70, 66, 30, 87, 18,  5],
       [11,  0, 12, 16, 12, 80, 45, 15, 77, 18],
       [43, 62, 46, 35, 14, 13, 45, 32, 28, 74],
       [40, 80, 90, 34, 11, 74, 96, 20,  2, 78],
       [59, 77,  1,  5, 63, 31, 64, 12, 23, 68],
       [71, 97, 49, 44,  3, 42, 41, 44, 23, 96],
       [ 6, 39, 32, 95, 81,  8, 85, 60, 10, 16],
       [12, 77, 67, 78, 33, 22, 79, 84, 44, 87],
       [62, 61, 27, 19, 12, 32, 27, 40, 21, 57],
       [33, 42, 93,  5, 79, 85, 16, 49, 25, 63]])

In [140]:
arr2[2,7]

32

In [142]:
arr2[5,-2]

23

In [144]:
arr2[-3,-5]

22

In [146]:
arr2

array([[71, 28, 53, 92, 70, 66, 30, 87, 18,  5],
       [11,  0, 12, 16, 12, 80, 45, 15, 77, 18],
       [43, 62, 46, 35, 14, 13, 45, 32, 28, 74],
       [40, 80, 90, 34, 11, 74, 96, 20,  2, 78],
       [59, 77,  1,  5, 63, 31, 64, 12, 23, 68],
       [71, 97, 49, 44,  3, 42, 41, 44, 23, 96],
       [ 6, 39, 32, 95, 81,  8, 85, 60, 10, 16],
       [12, 77, 67, 78, 33, 22, 79, 84, 44, 87],
       [62, 61, 27, 19, 12, 32, 27, 40, 21, 57],
       [33, 42, 93,  5, 79, 85, 16, 49, 25, 63]])

In [150]:
arr2[::-1]  # Advanced slicing

array([[33, 42, 93,  5, 79, 85, 16, 49, 25, 63],
       [62, 61, 27, 19, 12, 32, 27, 40, 21, 57],
       [12, 77, 67, 78, 33, 22, 79, 84, 44, 87],
       [ 6, 39, 32, 95, 81,  8, 85, 60, 10, 16],
       [71, 97, 49, 44,  3, 42, 41, 44, 23, 96],
       [59, 77,  1,  5, 63, 31, 64, 12, 23, 68],
       [40, 80, 90, 34, 11, 74, 96, 20,  2, 78],
       [43, 62, 46, 35, 14, 13, 45, 32, 28, 74],
       [11,  0, 12, 16, 12, 80, 45, 15, 77, 18],
       [71, 28, 53, 92, 70, 66, 30, 87, 18,  5]])

In [154]:
arr2

array([[71, 28, 53, 92, 70, 66, 30, 87, 18,  5],
       [11,  0, 12, 16, 12, 80, 45, 15, 77, 18],
       [43, 62, 46, 35, 14, 13, 45, 32, 28, 74],
       [40, 80, 90, 34, 11, 74, 96, 20,  2, 78],
       [59, 77,  1,  5, 63, 31, 64, 12, 23, 68],
       [71, 97, 49, 44,  3, 42, 41, 44, 23, 96],
       [ 6, 39, 32, 95, 81,  8, 85, 60, 10, 16],
       [12, 77, 67, 78, 33, 22, 79, 84, 44, 87],
       [62, 61, 27, 19, 12, 32, 27, 40, 21, 57],
       [33, 42, 93,  5, 79, 85, 16, 49, 25, 63]])

In [156]:
arr2[::2]

array([[71, 28, 53, 92, 70, 66, 30, 87, 18,  5],
       [43, 62, 46, 35, 14, 13, 45, 32, 28, 74],
       [59, 77,  1,  5, 63, 31, 64, 12, 23, 68],
       [ 6, 39, 32, 95, 81,  8, 85, 60, 10, 16],
       [62, 61, 27, 19, 12, 32, 27, 40, 21, 57]])

In [162]:
arr2

array([[71, 28, 53, 92, 70, 66, 30, 87, 18,  5],
       [11,  0, 12, 16, 12, 80, 45, 15, 77, 18],
       [43, 62, 46, 35, 14, 13, 45, 32, 28, 74],
       [40, 80, 90, 34, 11, 74, 96, 20,  2, 78],
       [59, 77,  1,  5, 63, 31, 64, 12, 23, 68],
       [71, 97, 49, 44,  3, 42, 41, 44, 23, 96],
       [ 6, 39, 32, 95, 81,  8, 85, 60, 10, 16],
       [12, 77, 67, 78, 33, 22, 79, 84, 44, 87],
       [62, 61, 27, 19, 12, 32, 27, 40, 21, 57],
       [33, 42, 93,  5, 79, 85, 16, 49, 25, 63]])

In [164]:
arr2[::3]

array([[71, 28, 53, 92, 70, 66, 30, 87, 18,  5],
       [40, 80, 90, 34, 11, 74, 96, 20,  2, 78],
       [ 6, 39, 32, 95, 81,  8, 85, 60, 10, 16],
       [33, 42, 93,  5, 79, 85, 16, 49, 25, 63]])

In [168]:
arr2[::-3]

array([[33, 42, 93,  5, 79, 85, 16, 49, 25, 63],
       [ 6, 39, 32, 95, 81,  8, 85, 60, 10, 16],
       [40, 80, 90, 34, 11, 74, 96, 20,  2, 78],
       [71, 28, 53, 92, 70, 66, 30, 87, 18,  5]])

In [171]:
arr2

array([[71, 28, 53, 92, 70, 66, 30, 87, 18,  5],
       [11,  0, 12, 16, 12, 80, 45, 15, 77, 18],
       [43, 62, 46, 35, 14, 13, 45, 32, 28, 74],
       [40, 80, 90, 34, 11, 74, 96, 20,  2, 78],
       [59, 77,  1,  5, 63, 31, 64, 12, 23, 68],
       [71, 97, 49, 44,  3, 42, 41, 44, 23, 96],
       [ 6, 39, 32, 95, 81,  8, 85, 60, 10, 16],
       [12, 77, 67, 78, 33, 22, 79, 84, 44, 87],
       [62, 61, 27, 19, 12, 32, 27, 40, 21, 57],
       [33, 42, 93,  5, 79, 85, 16, 49, 25, 63]])

In [173]:
arr2[::-4]

array([[33, 42, 93,  5, 79, 85, 16, 49, 25, 63],
       [71, 97, 49, 44,  3, 42, 41, 44, 23, 96],
       [11,  0, 12, 16, 12, 80, 45, 15, 77, 18]])

In [177]:
arr

array([0, 1, 2, 3, 4, 5])

In [179]:
arr.max()

5

In [181]:
arr.min()

0

In [183]:
arr

array([0, 1, 2, 3, 4, 5])

In [185]:
arr.mean()

2.5

In [187]:
arr

array([0, 1, 2, 3, 4, 5])

In [200]:
from numpy import*
a = array([1,2,3,4,5,6,7])
median(a)

4.0

In [202]:
arr

array([0, 1, 2, 3, 4, 5])

In [204]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [206]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [208]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [210]:
arr.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [214]:
arr.reshape(3,2,order='A')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [218]:
arr.reshape(3,2,order='F')

array([[0, 3],
       [1, 4],
       [2, 5]])

# Indexing

In [9]:
import numpy as np

In [11]:
mat = np.arange(0,100).reshape(10,10)

In [223]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
row = 4
col = 5

In [34]:
col

5

In [36]:
row

4

In [233]:
mat[row,col]

45

In [13]:
mat[4,5]

45

In [15]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [43]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [45]:
col = 6

In [20]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [22]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [24]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [38]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [40]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [47]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [49]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [51]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [55]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [66]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [72]:
mat[-3,:]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [74]:
mat[:,-3]

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [76]:
mat[1,4]

14

In [78]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [80]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [82]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [86]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [88]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [92]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [94]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [96]:
mat[::3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [98]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [100]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [102]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [104]:
mat[2:4,3:6]

array([[23, 24, 25],
       [33, 34, 35]])